project:
  type: website
  output-dir: _site

website:
  title: "[À COMPLÉTER : Prénom Nom]"
  site-url: "https://solinga87.github.io"
  search: true
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Accueil
      - href: research.qmd
        text: Recherche
      - href: contact.qmd
        text: Contact
  page-footer:
    center: "© 2026 [À COMPLÉTER : Prénom Nom]"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    grid:
      body-width: 800px

lang: fr
